version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --delete . "s3://codepipeline-us-east-1-179904591538"
 post_build:
   commands:
     - echo "post_build step"